### ISSUE TITLE
Compile time error on Linux

### ISSUE THREAD

**Issue by squidink7** [Zetalon0/Napocoin#3]
```
  CXX      qt/test/test_napocoin_qt-test_main.o
wallet/test/init_test_fixture.cpp: In constructor ‘InitWalletDirTestingSetup::InitWalletDirTestingSetup(const std::string&)’:
wallet/test/init_test_fixture.cpp:32:52: error: ‘std::map<std::__cxx11::basic_string<char>, boost::filesystem::path>::mapped_type’ {aka ‘class boost::filesystem::path’} has no member named ‘BOOST_FILESYSTEM_C_STR’
   32 |     std::ofstream f(m_walletdir_path_cases["file"].BOOST_FILESYSTEM_C_STR);
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:11902: wallet/test/test_test_napocoin-init_test_fixture.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/tmp/squidink7/Napocoin/src'
make[1]: *** [Makefile:13086: all-recursive] Error 1
make[1]: Leaving directory '/tmp/squidink7/Napocoin/src'
make: *** [Makefile:780: all-recursive] Error 1
```

Seems to be boost related. I'll try to mess around with the libraries and see where I can get this.

Out of curiosity, what's this a fork of? I'll try and build it and see if the error occurs upstream.

**Comment by squidink7** [comment]
Ok, just tried building litecoin and found the same error there. Turns out it's a known issue with new versions of boost (arch linux is newer than ubuntu which is why I'm getting the error and you're not). This has been fixed in the bitcoin codebase.
Try merging https://github.com/bitcoin/bitcoin/commit/d9b18c12903e3ed3b06e1452852159e5b713ff28 and I'll let you know if it works.

**Comment by squidink7** [comment]
Got another error that was fixed with https://github.com/litecoin-project/litecoin/pull/650/commits/990d5e8fa20b7d6b4b8c629d143e180437ecdffc
Will open a pull request for both of these changes, although I now have a successful build!

**Comment by squidink7** [comment]
Opened a pull request #5

**Comment by Zetalon0** [comment]
> Got another error that was fixed with [litecoin-project/litecoin@990d5e8](https://github.com/litecoin-project/litecoin/commit/990d5e8fa20b7d6b4b8c629d143e180437ecdffc) Will open a pull request for both of these changes, although I now have a successful build! ![image](https://user-images.githubusercontent.com/56238661/196854138-c6b7ae3c-17f1-48c6-af20-82414ef659be.png)

can it run correctly after you press ok?

**Comment by squidink7** [comment]
Yes, it launches and runs fine (although I'm offline so it hasn't done a sync)

**Comment by Zetalon0** [comment]
how i still get 
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::replace: __pos (which is 18446744073709551615) > this->size() (which is 13)
Aborted (core dumped)
```

**Comment by squidink7** [comment]
It might be Ubuntus old version of qt. I can send a link to my build if you want to try that one

**Comment by Zetalon0** [comment]
that would be great thx

**Comment by squidink7** [comment]
https://woodcroftcollege-my.sharepoint.com/:u:/g/personal/fryer_r_woodcroft_sa_edu_au/Ef9--dh7eJJEnzLf55iiqnUB7Ds5_f2NSikPD1uIiJKi3Q?e=KC6fBv

**Comment by squidink7** [comment]
If that doesn't work all I can suggest is updating your ubuntu vm

**Comment by squidink7** [comment]
Let me know how it goes, I'm curious

**Comment by Zetalon0** [comment]
I tryed to run yours and it give out:
`error while loading shared libraries: libboost_system.so.1.80.0: cannot open shared object file: No such file or directory`

**Comment by squidink7** [comment]
Ahh, I see. Looks like our versions of boost are out of sync. If you give me a bit I can put together an app bundle that contains boost and maybe qt as well if yours doesn't work

**Comment by squidink7** [comment]
[try this](https://woodcroftcollege-my.sharepoint.com/:u:/g/personal/fryer_r_woodcroft_sa_edu_au/EXvFHuseWypGuOIb1vqkvOYB7hWpgUz9dpcaastDFzxWiA?e=Dfhx0a)

**Comment by squidink7** [comment]
wait never mind

**Comment by squidink7** [comment]
[try this version](https://woodcroftcollege-my.sharepoint.com/:u:/g/personal/fryer_r_woodcroft_sa_edu_au/EQwXtdNnRehEmaA5BG2DY88Bhe7XhYUEZwJvIxiS88iBoQ?e=9XrLhQ)

**Comment by Zetalon0** [comment]
error while loading shared libraries: libprotobuf.so.32: cannot open shared object file: No such file or directory

**Comment by squidink7** [comment]
[keep telling me what libraries are missing and I'll keep adding them (or we can just work together on this at lunch tomorrow)](https://filebin.net/b3yuw8age9eh5pmg)

**Comment by squidink7** [comment]
the 2.0 branch just finished compiling and I'm getting the same error as https://github.com/Zetalon0/Napocoin/issues/1. Will close in favour of that issue.
